CREATE OR REPLACE VIEW G_ORDERS_BY_PAYMENT_METHOD AS
SELECT
  REF.REF_PAYMENT_METHOD,
  PAY.DES_PAYMENT_METHOD,
  COUNT(*) AS NUM_ORDERS,
  SUM(QTY_ORDERED) AS TOTAL_QTY,
  SUM(AMT_TOTAL) AS TOTAL_REVENUE
FROM S_ORDERS_CLEAN_COMPLEX REF
LEFT JOIN S_PAYMENT_METHODS PAY
ON REF.REF_PAYMENT_METHOD = PAY.REF_PAYMENT_METHOD
GROUP BY REF.REF_PAYMENT_METHOD, PAY.DES_PAYMENT_METHOD;


-- GOLD
-- TOP TEN CLIENTES QUE HAN COMPRADO MÁS PIEZAS,para hacer campañas de fidelización o premios a los mejores clientes 

CREATE OR REPLACE VIEW G_TOP_TEN_CLIENTS_QTY AS
SELECT ID_CUSTOMER,SUM(QTY_ORDERED) AS NUMPIEZAS_TOTAL FROM S_ORDERS_CLEAN_COMPLEX ORD
WHERE QTY_ORDERED IS NOT NULL
GROUP BY ID_CUSTOMER
ORDER BY NUMPIEZAS_TOTAL DESC
LIMIT 10

--TOP TEN CLIENTES QUE HAN GASTADO MÁS
-- para hacer algún regalo/premio a esos clientes o descuentos en las siguientes compras

CREATE OR REPLACE VIEW G_TOP_TEN_CLIENTS_IMPORT AS
SELECT ID_CUSTOMER, SUM(AMT_TOTAL) AS TOTAL -- C0362 4278
FROM S_ORDERS_CLEAN_COMPLEX
WHERE AMT_TOTAL IS NOT NULL
GROUP BY ID_CUSTOMER
ORDER BY TOTAL DESC
LIMIT 10

-- TOP TEN PIEZAS MÁS VENDIDAS
-- para poder organizar mejor el stock
CREATE OR REPLACE VIEW G_TOP_TEN_PARTS AS
SELECT ID_PART,SUM(QTY_ORDERED) AS NUMPIEZAS_TOTAL FROM S_ORDERS_CLEAN_COMPLEX ORD
WHERE QTY_ORDERED IS NOT NULL
GROUP BY ID_PART
ORDER BY NUMPIEZAS_TOTAL DESC
LIMIT 10

--  TOP TEN DE MES EN QUE SE HAN PEDIDO MÁS PIEZAS
-- para organizar mejor el stock y estar preparados en los meses punta

CREATE OR REPLACE VIEW G_TOP_TEN_MONTH AS
SELECT   
EXTRACT(MONTH FROM DTE_ORDER) AS MES, 
SUM(QTY_ORDERED) AS PIEZAS_PEDIDAS,
EXTRACT(DAYOFWEEK FROM DTE_ORDER) AS DIA_SEMANA,
DTE_ORDER AS FECHA_COMPLETA 
FROM S_ORDERS_CLEAN_COMPLEX
WHERE QTY_ORDERED IS NOT NULL
GROUP BY DTE_ORDER
ORDER BY PIEZAS_PEDIDAS DESC
LIMIT 10