CREATE OR REPLACE VIEW G_ORDERS_BY_PAYMENT_METHOD AS
SELECT
  REF.REF_PAYMENT_METHOD,
  PAY.DES_PAYMENT_METHOD,
  COUNT(*) AS NUM_ORDERS,
  SUM(QTY_ORDERED) AS TOTAL_QTY,
  SUM(AMT_TOTAL) AS TOTAL_REVENUE
FROM S_ORDERS_CLEAN_COMPLEX REF
LEFT JOIN S_PAYMENT_METHODS PAY
ON REF.REF_PAYMENT_METHOD = PAY.REF_PAYMENT_METHOD
GROUP BY REF.REF_PAYMENT_METHOD, PAY.DES_PAYMENT_METHOD;